services:
  - type: web
    name: betpro-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PESAPAL_ENV
        value: sandbox
      - key: PESAPAL_CONSUMER_KEY
        sync: false
      - key: PESAPAL_CONSUMER_SECRET
        sync: false
      - key: PESAPAL_IPN_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
